#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════
# pin-deps.sh — generate requirements-lock.txt from the RUNNING prod image
#
# Why this exists:
#   Local Python is 3.13; the prod image is 3.11. A lockfile generated
#   locally would pin packages that may not resolve on 3.11. The only
#   safe way to pin is to ask the actual image what it has.
#
# When to run:
#   After requirements.txt changes, before a deploy.
#
# Effect:
#   Writes core/requirements-lock.txt with `pip freeze` output from the
#   running market-terminal container.
#
# Usage (from the repo root inside core/):
#   bash scripts/pin-deps.sh
#
# Prereq: market-terminal container must be running locally.
# ═══════════════════════════════════════════════════════════════════════════

set -e

CONTAINER="${1:-market-terminal}"
OUT="${2:-requirements-lock.txt}"

if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
  echo "❌ container '${CONTAINER}' is not running."
  echo "   Start it first: docker compose -f docker-compose.yml up -d"
  exit 1
fi

echo "  📦 Reading installed packages from container '${CONTAINER}'..."
docker exec "${CONTAINER}" pip freeze --disable-pip-version-check > "${OUT}"

# Add a header note so users know how this file was made
HEADER="# Generated by scripts/pin-deps.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source: docker exec ${CONTAINER} pip freeze
# Python: $(docker exec "${CONTAINER}" python --version | awk '{print $2}')
# Image:  $(docker inspect --format='{{.Config.Image}}' "${CONTAINER}")
#
# To install matching versions in a new environment:
#   pip install -r requirements-lock.txt
# To regenerate after updating requirements.txt:
#   bash scripts/pin-deps.sh
"
TMP=$(mktemp)
echo "$HEADER" > "$TMP"
cat "${OUT}" >> "$TMP"
mv "$TMP" "${OUT}"

LINES=$(wc -l < "${OUT}" | tr -d ' ')
echo "  ✅ Wrote ${OUT} (${LINES} lines)"
echo ""
echo "  Diff vs requirements.txt declared packages:"
echo "  ----------------------------------------"
# show which declared packages are missing from the lock and which extras are present
declared=$(grep -oE '^[a-zA-Z0-9_.-]+' requirements.txt | sort -u)
locked=$(grep -oE '^[a-zA-Z0-9_.-]+' "${OUT}" | sort -u)
echo "  In requirements.txt but NOT in lock (suspicious):"
comm -23 <(echo "$declared") <(echo "$locked" | tr '[:upper:]' '[:lower:]') | sed 's/^/    /'
echo ""
echo "  Next step: git add ${OUT} && git commit -m 'chore: pin dependencies from prod image'"
